from decimal import Decimal

# User
MAX_EMAIL_LENGTH = 254
MAX_PASSWORD_HASH_LENGTH = 255
MIN_PASSWORD_LENGTH = 12
MAX_PASSWORD_LENGTH = 128
MAX_FIRST_NAME_LENGTH = 50
MAX_LAST_NAME_LENGTH = 50

# Artist / Album
MAX_ARTIST_NAME_LENGTH = 100
MAX_ALBUM_NAME_LENGTH = 150
# Album price — matches Numeric(10, 2) max
MAX_PRICE = Decimal("99999999.99")

# Address
MAX_STREET_LENGTH = 255
MAX_CITY_LENGTH = 100
MAX_POSTAL_CODE_LENGTH = 20
MAX_COUNTRY_CODE_LENGTH = 2

# Supplier
MAX_SUPPLIER_NAME_LENGTH = 150

# Invoice
MAX_INVOICE_NUMBER_LENGTH = 50
