"""Refactor order_items and supplier_order_items to composite primary keys & Enforce address-user ownership constraint

Revision ID: a09b12a8bc7c
Revises: 9b4432b71b35
Create Date: 2026-05-21 10:09:47.393907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09b12a8bc7c'
down_revision: Union[str, Sequence[str], None] = '9b4432b71b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_addresses_id_user', 'addresses', ['id', 'user_id'])
    op.drop_column('order_items', 'id')
    op.drop_constraint(op.f('orders_address_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_address_owner', 'orders', 'addresses', ['address_id', 'user_id'], ['id', 'user_id'])
    op.drop_column('supplier_order_items', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_order_items', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('fk_orders_address_owner', 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_address_id_fkey'), 'orders', 'addresses', ['address_id'], ['id'])
    op.add_column('order_items', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('uq_addresses_id_user', 'addresses', type_='unique')
    # ### end Alembic commands ###
