"""Refactor user_id foreign key in orders table & Rename password_hash to hashed_password in users table

Revision ID: b04ef5914235
Revises: 54a7eb242515
Create Date: 2026-05-25 15:07:56.449982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04ef5914235'
down_revision: Union[str, Sequence[str], None] = '54a7eb242515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.execute('UPDATE users SET password_hash = hashed_password')
    op.alter_column('users', 'password_hash', nullable=False)
    op.drop_column('users', 'hashed_password')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
